[options]
;Security
admin_passwd = 123456
addons_path = D:\odoo19\COOLAGE\odoo\addons,D:\\odoo19\\COOLAGE\\custom_addons
data_dir = D:\odoo19\.local
http_interface = 127.0.0.1
http_port = 8069

db_host = localhost
db_port = 5433
db_user = odoo19
db_password = odoo19

log_level = info
