from . import student
from . import skills
from . import department
from . import attendance
from . import leave
from . import subject
from . import student_exam
from . import student_mark
from . import student_marks_line
from . import bulk_password_reset
from . import student_score_record
from . import res_partner
